#!/usr/bin/env python3
"""Update css-prefixer and html-sanitizer with full metadata"""
import json

with open('tools.json', 'r', encoding='utf-8') as f:
    tools = json.load(f)

# CSS Prefixer metadata
css_data = {
    "icon": "🎨",
    "long_zh": '<p>免费的在线 CSS 浏览器前缀添加器。<strong>自动为 CSS 属性添加 -webkit-、-moz-、-ms-、-o- 浏览器供应商前缀</strong>，确保 CSS3 新特性（如 transform、animation、transition、flexbox、grid、mask、filter 等）在旧版浏览器中正常工作。</p><p>支持 60+ 常见需要前缀的 CSS 属性，支持 @keyframes 规则前缀化，支持 gradient 等函数值前缀化。所有处理在浏览器本地完成，CSS 代码不会上传到服务器。</p>',
    "long_en": '<p>Free online CSS vendor prefixer tool. <strong>Automatically add -webkit-, -moz-, -ms-, -o- vendor prefixes</strong> to CSS properties, ensuring CSS3 features work in older browsers.</p><p>Supports 60+ commonly prefixed CSS properties, @keyframes rule prefixing, and gradient function value prefixing. All processing is done locally in your browser.</p>',
    "seo_title_zh": 'CSS 前缀添加器 | 在线 CSS 浏览器前缀自动生成工具',
    "seo_title_en": 'CSS Prefixer - Free Online Vendor Prefix Generator | AI Toolbox',
    "features_zh": ['自动添加 -webkit-、-moz-、-ms-、-o- 浏览器前缀', '支持 transform、animation、transition 等 60+ CSS 属性', '支持 @keyframes 规则前缀化', '支持 gradient 函数值前缀处理', '支持 flexbox、grid 等布局属性前缀', '完全本地处理，CSS 代码不上传服务器'],
    "features_en": ['Auto-add -webkit-, -moz-, -ms-, -o- vendor prefixes', 'Supports 60+ CSS properties including transform, animation, transition', 'Supports @keyframes rule prefixing', 'Supports gradient function value prefixing', 'Supports flexbox, grid layout property prefixes', '100% local processing, no CSS upload'],
    "faq_zh": [['为什么要添加 CSS 浏览器前缀？', '不同浏览器引擎对 CSS3 新特性的实现阶段不同，需要添加供应商前缀来确保兼容性。'], ['支持哪些 CSS 属性？', '支持 transform、animation、transition、flexbox、grid、mask、filter 等 60+ 属性。'], ['支持 @keyframes 吗？', '支持。@keyframes 规则会自动生成 -webkit-、-moz-、-o- 前缀版本。'], ['支持 gradient 值前缀吗？', '支持。linear-gradient、radial-gradient、conic-gradient 等函数值会自动添加 -webkit- 前缀。'], ['数据安全吗？', '完全安全。所有 CSS 处理在浏览器本地完成，代码不会上传到服务器。'], ['和 Autoprefixer 有什么区别？', '功能类似，但本工具完全在浏览器本地运行，无需安装任何软件或依赖。']],
    "faq_en": [['Why add vendor prefixes?', 'Different browser engines implement CSS3 features at different stages. Vendor prefixes ensure compatibility across older browsers.'], ['Which CSS properties are supported?', '60+ properties including transform, animation, transition, flexbox, grid, mask, filter.'], ['Does it support @keyframes?', 'Yes. @keyframes rules are automatically prefixed with vendor prefixes.'], ['Does it support gradient values?', 'Yes. Functions like linear-gradient, radial-gradient get -webkit- prefix.'], ['Is my data safe?', 'Completely safe. All CSS processing is done locally in your browser.'], ['How is this different from Autoprefixer?', 'Similar functionality but runs entirely in the browser - no installation needed.']],
    "keywords_zh": 'CSS前缀,浏览器前缀,webkit,moz,ms,o,CSS兼容,浏览器兼容,css3前缀,自动添加前缀,autoprefixer,前端兼容,跨浏览器css',
    "keywords_en": 'CSS prefix, vendor prefix, autoprefixer, webkit prefix, moz prefix, ms prefix, o prefix, CSS compatibility, cross-browser CSS, CSS3 prefix',
    "ui_zh": '<div class="tool-controls">\n<div style="margin-bottom:8px;display:flex;gap:8px;flex-wrap:wrap">\n<button class="btn" id="cp-prefix">🔧 添加前缀</button>\n<button class="btn btn-secondary" id="cp-copy">📋 复制结果</button>\n<button class="btn btn-secondary" id="cp-clear">🗑️ 清空</button>\n</div>\n<div style="display:flex;gap:12px;flex-wrap:wrap">\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">CSS 输入</label>\n<textarea id="cp-input" style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-card);resize:vertical" placeholder="粘贴 CSS 代码..."></textarea>\n</div>\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">添加前缀后的 CSS</label>\n<textarea id="cp-output" readonly style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-subtle);resize:vertical" placeholder="前缀添加后的 CSS 将显示在这里..."></textarea>\n</div>\n</div>\n<div id="cp-msg" style="margin-top:8px;font-size:13px"></div>\n<div style="margin-top:12px;padding:8px 12px;background:var(--bg-warning-light);border:1px solid var(--border);border-radius:8px;font-size:13px;color:var(--text-dim)"><strong>🔒 隐私提示</strong>：所有处理在浏览器本地完成，CSS 代码不会上传到服务器。</div>\n</div>',
    "ui_en": '<div class="tool-controls">\n<div style="margin-bottom:8px;display:flex;gap:8px;flex-wrap:wrap">\n<button class="btn" id="cp-prefix">🔧 Add Prefixes</button>\n<button class="btn btn-secondary" id="cp-copy">📋 Copy Result</button>\n<button class="btn btn-secondary" id="cp-clear">🗑️ Clear</button>\n</div>\n<div style="display:flex;gap:12px;flex-wrap:wrap">\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">CSS Input</label>\n<textarea id="cp-input" style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-card);resize:vertical" placeholder="Paste CSS code..."></textarea>\n</div>\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">Prefixed CSS</label>\n<textarea id="cp-output" readonly style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-subtle);resize:vertical" placeholder="Prefixed CSS will appear here..."></textarea>\n</div>\n</div>\n<div id="cp-msg" style="margin-top:8px;font-size:13px"></div>\n<div style="margin-top:12px;padding:8px 12px;background:var(--bg-warning-light);border:1px solid var(--border);border-radius:8px;font-size:13px;color:var(--text-dim)"><strong>🔒 Privacy</strong>: All processing is local. No CSS upload.</div>\n</div>'
}

# HTML Sanitizer metadata
html_data = {
    "icon": "🛡️",
    "long_zh": '<p>免费的在线 HTML 净化器。<strong>安全地清洗 HTML 代码，移除 XSS（跨站脚本）攻击向量、恶意脚本、危险标签和事件处理器</strong>。支持两种模式：安全模式（清空脚本内容但保留标签结构）和严格模式（移除所有未知标签和脚本标签）。</p><p>基于白名单机制，只允许安全的 HTML 标签和属性，自动移除所有 on* 事件处理器、javascript: 协议链接等 XSS 向量。所有处理在浏览器本地完成，HTML 代码不会上传到服务器。</p>',
    "long_en": '<p>Free online HTML sanitizer tool. <strong>Safely clean HTML code by removing XSS vectors, malicious scripts, dangerous tags, and event handlers</strong>. Supports Safe mode (empties script content) and Strict mode (removes all unknown and script tags).</p><p>Whitelist-based approach ensures only safe HTML tags and attributes are allowed. All event handlers and javascript: protocol links are automatically removed.</p>',
    "seo_title_zh": 'HTML 净化器 | 在线 XSS 防护 HTML 安全清洗工具',
    "seo_title_en": 'HTML Sanitizer - Free Online XSS Protection & HTML Cleaner | AI Toolbox',
    "features_zh": ['移除 XSS 攻击向量（javascript:、data: 等危险协议）', '移除所有 on* 事件处理器（onclick、onload、onsubmit 等）', '安全模式：保留标签结构，清空脚本内容', '严格模式：移除所有未知标签和脚本标签', '基于白名单的标签和属性过滤', '完全本地处理，HTML 代码不上传服务器'],
    "features_en": ['Remove XSS vectors (javascript:, data: and other dangerous protocols)', 'Remove all on* event handlers', 'Safe mode: preserve tag structure, empty script content', 'Strict mode: remove all unknown tags and script tags', 'Whitelist-based tag and attribute filtering', '100% local processing, no HTML upload'],
    "faq_zh": [['什么是 XSS 攻击？', 'XSS（跨站脚本攻击）是攻击者通过注入恶意脚本到网页中来窃取用户数据或劫持会话的攻击方式。HTML 净化器可以移除这些恶意代码。'], ['安全模式和严格模式有什么区别？', '安全模式会清空脚本和样式的内容但保留标签本身。严格模式会完全移除所有未知和危险的标签。'], ['支持哪些 HTML 标签？', '支持所有标准的安全 HTML 标签，包括标题、段落、列表、表格、表单、媒体元素等。'], ['会移除 style 属性吗？', '不会。合法的 style 属性会被保留，但所有 on* 事件处理器都会被移除。'], ['数据安全吗？', '完全安全。所有处理在浏览器本地完成，HTML 代码不会上传到服务器。'], ['适合什么场景使用？', '适合用户输入内容展示前的安全清洗、富文本编辑器输出过滤、HTML 邮件内容安全处理等场景。']],
    "faq_en": [['What is XSS?', 'XSS (Cross-Site Scripting) is a security vulnerability where attackers inject malicious scripts into web pages. HTML sanitizer removes these.']],
    "keywords_zh": 'HTML净化,XSS防护,跨站脚本防护,HTML清洗,HTML安全,过滤HTML,移除脚本,安全HTML,输入净化,前端安全,web安全',
    "keywords_en": 'HTML sanitizer, XSS protection, HTML cleaner, HTML filter, remove scripts, safe HTML, HTML security, cross-site scripting prevention',
    "ui_zh": '<div class="tool-controls">\n<div style="margin-bottom:8px;display:flex;gap:8px;flex-wrap:wrap;align-items:center">\n<button class="btn" id="hs-sanitize">🛡️ 净化 HTML</button>\n<button class="btn btn-secondary" id="hs-copy">📋 复制结果</button>\n<button class="btn btn-secondary" id="hs-clear">🗑️ 清空</button>\n<label style="display:flex;align-items:center;gap:4px;font-size:13px;margin-left:8px"><input type="radio" name="hs-mode" value="safe" checked> 安全模式</label>\n<label style="display:flex;align-items:center;gap:4px;font-size:13px"><input type="radio" name="hs-mode" value="strict"> 严格模式</label>\n</div>\n<div style="display:flex;gap:12px;flex-wrap:wrap">\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">HTML 输入</label>\n<textarea id="hs-input" style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-card);resize:vertical" placeholder="粘贴 HTML 代码..."></textarea>\n</div>\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">净化后的 HTML</label>\n<textarea id="hs-output" readonly style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-subtle);resize:vertical" placeholder="净化后的 HTML 将显示在这里..."></textarea>\n</div>\n</div>\n<div id="hs-msg" style="margin-top:8px;font-size:13px"></div>\n<div style="margin-top:12px;padding:8px 12px;background:var(--bg-warning-light);border:1px solid var(--border);border-radius:8px;font-size:13px;color:var(--text-dim)"><strong>🔒 隐私提示</strong>：所有处理在浏览器本地完成，HTML 代码不会上传到服务器。</div>\n</div>',
    "ui_en": '<div class="tool-controls">\n<div style="margin-bottom:8px;display:flex;gap:8px;flex-wrap:wrap;align-items:center">\n<button class="btn" id="hs-sanitize">🛡️ Sanitize HTML</button>\n<button class="btn btn-secondary" id="hs-copy">📋 Copy Result</button>\n<button class="btn btn-secondary" id="hs-clear">🗑️ Clear</button>\n<label style="display:flex;align-items:center;gap:4px;font-size:13px;margin-left:8px"><input type="radio" name="hs-mode" value="safe" checked> Safe</label>\n<label style="display:flex;align-items:center;gap:4px;font-size:13px"><input type="radio" name="hs-mode" value="strict"> Strict</label>\n</div>\n<div style="display:flex;gap:12px;flex-wrap:wrap">\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">HTML Input</label>\n<textarea id="hs-input" style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-card);resize:vertical" placeholder="Paste HTML code..."></textarea>\n</div>\n<div style="flex:1;min-width:300px">\n<label style="font-size:13px;font-weight:600;display:block;margin-bottom:4px">Sanitized HTML</label>\n<textarea id="hs-output" readonly style="width:100%;min-height:350px;font-family:Consolas,monospace;font-size:13px;padding:10px;border:1px solid var(--border);border-radius:6px;background:var(--bg-subtle);resize:vertical" placeholder="Sanitized HTML will appear here..."></textarea>\n</div>\n</div>\n<div id="hs-msg" style="margin-top:8px;font-size:13px"></div>\n<div style="margin-top:12px;padding:8px 12px;background:var(--bg-warning-light);border:1px solid var(--border);border-radius:8px;font-size:13px;color:var(--text-dim)"><strong>🔒 Privacy</strong>: All processing is local. No HTML upload.</div>\n